# Nome do Nosso Workflow
name: Meu Primeiro CI
# Definir o gatilho do nosso workflow
on:
    push
# Definir os Jobs
jobs:
    # Definir o nome do job
    build:
        # O executor
        runs-on: ubuntu-latest
    
    # Passos
    steps:
        
        - uses: actions/checkout@v4

        # Identificando nossos passaos de execução
        - name: Run a one-line script
          run: echo Hello, world!
        
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
        

        
