# Nome do Nosso Workflow
name: Meu Primeiro CI com github actions

# Definir o gatilho do nosso workflow
on:
    push
# Definir os Jobs
jobs:
    # Definir o nome do job
  build:
    name: Job de Build
        # O executor
    runs-on: ubuntu-latest
    
    # Passos
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

      # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

      # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
          echo Add other actions to build,
          echo test, and deploy your project.


        
